---
name: golangci
on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=5m --tests=false
  test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Run tests with CI Visibility
        uses: Harbor-Engineering/harbor-github-actions/harbor-health/actions/run-go-tests-and-publish@v1
        with:
          enable-dd-trace: true
          datadog-service: go-athenahealth
          datadog-api-key: ${{ secrets.DD_API_KEY }}
          datadog-extra-tags: 'team:platform layer:ehr-client'
